/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.game {
    export class GameHomeViewUI extends Laya.Scene {
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
		public back_btn:Laya.Sprite;
		public imageBtStartGame:Laya.Image;
		public boxFun:Laya.Box;
		public imageBtShare:Laya.Image;
		public imageBtChoseLevel:Laya.Image;
		public imageBtSign:Laya.Image;
		public imageBtInvital:Laya.Image;
		public boxLevel:Laya.Box;
		public spLevelNum:Laya.Sprite;
		public btn_more:Laya.Sprite;
		public imageWeCatMoreGame:Laya.Image;
		public more_games:Laya.Image;
		public image_wm:Laya.Image;
		public btn_colorSign:Laya.Button;
		public btn_lottery:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameHomeView");
        }
    }
    REG("ui.game.GameHomeViewUI",GameHomeViewUI);
    export class GameViewUI extends Laya.Scene {
		public boxBtList:Laya.Box;
		public imageBtGotoNextLevel:Laya.Image;
		public imageBtTip:Laya.Image;
		public imageBtRestart:Laya.Image;
		public imageBtToHome:Laya.Image;
		public boxLevelInfo:Laya.HBox;
		public spLevelLeft:Laya.Sprite;
		public hBoxIndex:Laya.HBox;
		public spLevelRight:Laya.Sprite;
		public box_choose:Laya.Box;
		public icon_chooseRight:Laya.Image;
		public icon_right:Laya.Image;
		public icon_choseCoverUpRight:Laya.Image;
		public icon_chooseLeft:Laya.Image;
		public icon_left:Laya.Image;
		public icon_choseCoverUpLeft:Laya.Image;
		public imageHand:Laya.Image;
		public choosesuper_light:Laya.Image;
		public icon_chooseSuper:Laya.Image;
		public icon_super:Laya.Image;
		public starOne:Laya.Image;
		public starTwo:Laya.Image;
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
		public imageTTVideo:Laya.Image;
		public image_wm:Laya.Image;
		public imageWeCatMoreGame:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameView");
        }
    }
    REG("ui.game.GameViewUI",GameViewUI);
}
export module ui.game.level_ks {
    export class KsLevelScene1UI extends Laya.Scene {
		public icon_bg:Laya.Box;
		public box_game:Laya.Box;
		public box_waterup:Laya.Box;
		public boxDialog:Laya.Box;
		public boxDowmTotal:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene1");
        }
    }
    REG("ui.game.level_ks.KsLevelScene1UI",KsLevelScene1UI);
    export class KsLevelScene10UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene10");
        }
    }
    REG("ui.game.level_ks.KsLevelScene10UI",KsLevelScene10UI);
    export class KsLevelScene11UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene11");
        }
    }
    REG("ui.game.level_ks.KsLevelScene11UI",KsLevelScene11UI);
    export class KsLevelScene12UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene12");
        }
    }
    REG("ui.game.level_ks.KsLevelScene12UI",KsLevelScene12UI);
    export class KsLevelScene13UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_duwu:Laya.Box;
		public box_enb:Laya.Box;
		public box_heipao:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_dowm:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene13");
        }
    }
    REG("ui.game.level_ks.KsLevelScene13UI",KsLevelScene13UI);
    export class KsLevelScene14UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_gou:Laya.Box;
		public box_enb:Laya.Box;
		public image_fj:Laya.Image;
		public box_player:Laya.Box;
		public box_frame:Laya.Box;
		public boxDialog:Laya.Box;
		public box_dowm:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene14");
        }
    }
    REG("ui.game.level_ks.KsLevelScene14UI",KsLevelScene14UI);
    export class KsLevelScene15UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_right:Laya.Box;
		public box_left:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene15");
        }
    }
    REG("ui.game.level_ks.KsLevelScene15UI",KsLevelScene15UI);
    export class KsLevelScene16UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_frame:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene16");
        }
    }
    REG("ui.game.level_ks.KsLevelScene16UI",KsLevelScene16UI);
    export class KsLevelScene17UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene17");
        }
    }
    REG("ui.game.level_ks.KsLevelScene17UI",KsLevelScene17UI);
    export class KsLevelScene18UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_down:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene18");
        }
    }
    REG("ui.game.level_ks.KsLevelScene18UI",KsLevelScene18UI);
    export class KsLevelScene19UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_down:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene19");
        }
    }
    REG("ui.game.level_ks.KsLevelScene19UI",KsLevelScene19UI);
    export class KsLevelScene2UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene2");
        }
    }
    REG("ui.game.level_ks.KsLevelScene2UI",KsLevelScene2UI);
    export class KsLevelScene20UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_down:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene20");
        }
    }
    REG("ui.game.level_ks.KsLevelScene20UI",KsLevelScene20UI);
    export class KsLevelScene21UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_1:Laya.Box;
		public box_2:Laya.Box;
		public box_down:Laya.Box;
		public box_enb:Laya.Box;
		public box_oper:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public image_frame:Laya.Image;
		public box_frame:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene21");
        }
    }
    REG("ui.game.level_ks.KsLevelScene21UI",KsLevelScene21UI);
    export class KsLevelScene22UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public sp_nainao:Laya.Sprite;
		public box_player:Laya.Box;
		public box_frame:Laya.Box;
		public box_down:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene22");
        }
    }
    REG("ui.game.level_ks.KsLevelScene22UI",KsLevelScene22UI);
    export class KsLevelScene23UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_down:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene23");
        }
    }
    REG("ui.game.level_ks.KsLevelScene23UI",KsLevelScene23UI);
    export class KsLevelScene24UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene24");
        }
    }
    REG("ui.game.level_ks.KsLevelScene24UI",KsLevelScene24UI);
    export class KsLevelScene25UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_power:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene25");
        }
    }
    REG("ui.game.level_ks.KsLevelScene25UI",KsLevelScene25UI);
    export class KsLevelScene26UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_long:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene26");
        }
    }
    REG("ui.game.level_ks.KsLevelScene26UI",KsLevelScene26UI);
    export class KsLevelScene27UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_yun2:Laya.Box;
		public box_player:Laya.Box;
		public box_yun1:Laya.Box;
		public image_yun1:Laya.Image;
		public image_yun2:Laya.Image;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene27");
        }
    }
    REG("ui.game.level_ks.KsLevelScene27UI",KsLevelScene27UI);
    export class KsLevelScene28UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_up:Laya.Box;
		public box_down:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene28");
        }
    }
    REG("ui.game.level_ks.KsLevelScene28UI",KsLevelScene28UI);
    export class KsLevelScene29UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_power:Laya.Box;
		public spYue:Laya.Sprite;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene29");
        }
    }
    REG("ui.game.level_ks.KsLevelScene29UI",KsLevelScene29UI);
    export class KsLevelScene30UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_bottom:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene30");
        }
    }
    REG("ui.game.level_ks.KsLevelScene30UI",KsLevelScene30UI);
    export class KsLevelScene4UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene4");
        }
    }
    REG("ui.game.level_ks.KsLevelScene4UI",KsLevelScene4UI);
    export class KsLevelScene5UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_1:Laya.Box;
		public box_game_2:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene5");
        }
    }
    REG("ui.game.level_ks.KsLevelScene5UI",KsLevelScene5UI);
    export class KsLevelScene6UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_hd:Laya.Box;
		public box_cg1:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene6");
        }
    }
    REG("ui.game.level_ks.KsLevelScene6UI",KsLevelScene6UI);
    export class KsLevelScene7UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene7");
        }
    }
    REG("ui.game.level_ks.KsLevelScene7UI",KsLevelScene7UI);
    export class KsLevelScene8UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_1:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene8");
        }
    }
    REG("ui.game.level_ks.KsLevelScene8UI",KsLevelScene8UI);
    export class KsLevelScene9UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
		public box_enb:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level_ks/KsLevelScene9");
        }
    }
    REG("ui.game.level_ks.KsLevelScene9UI",KsLevelScene9UI);
}
export module ui.game.uiView {
    export class AddSpViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public btLable:Laya.Sprite;
		public imageBtGet:Laya.Box;
		public spNum:Laya.Sprite;
		public box_qq:Laya.Box;
		public box_index:Laya.Box;
		public box_up:Laya.Box;
		public box_down:Laya.Box;
		public box_lable:Laya.Box;
		public lable_number:Laya.Label;
		public btn_close:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/AddSpView");
        }
    }
    REG("ui.game.uiView.AddSpViewUI",AddSpViewUI);
    export class CommonViewUI extends Laya.Scene {
		public sp:Laya.Image;
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public glod:Laya.Image;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/CommonView");
        }
    }
    REG("ui.game.uiView.CommonViewUI",CommonViewUI);
    export class FailEntryOneViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public image_wm:Laya.Image;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spGlod:Laya.Sprite;
		public imageBtSign:Laya.Box;
		public boxAni:Laya.Box;
		public box_wecat:Laya.Box;
		public img_back:Laya.Image;
		public btLable:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/FailEntryOneView");
        }
    }
    REG("ui.game.uiView.FailEntryOneViewUI",FailEntryOneViewUI);
    export class FailEntryTwoViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public btLable:Laya.Sprite;
		public imageBtShare:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareName:Laya.Image;
		public ttGoodsType:Laya.Image;
		public ttSpecial:Laya.Sprite;
		public shareGlodCount:Laya.Sprite;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spCount:Laya.Sprite;
		public imageWeCatMoreGame:Laya.Image;
		public panelWeCatMoreGame:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public box_wecat:Laya.Box;
		public box_content:Laya.Box;
		public imageBtToHome:Laya.Image;
		public imageBtRestart:Laya.Box;
		public spCost:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/FailEntryTwoView");
        }
    }
    REG("ui.game.uiView.FailEntryTwoViewUI",FailEntryTwoViewUI);
    export class GuessLikeUI extends Laya.Scene {
		public panelList:Laya.Panel;
		public boxView:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/GuessLike");
        }
    }
    REG("ui.game.uiView.GuessLikeUI",GuessLikeUI);
    export class GuessLikeItemUI extends Laya.Scene {
		public icon_:Laya.Image;
		public iconMask_:Laya.Image;
		public name_txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/GuessLikeItem");
        }
    }
    REG("ui.game.uiView.GuessLikeItemUI",GuessLikeItemUI);
    export class InviteFriendsIndexViewUI extends Laya.Scene {
		public bg:Laya.Sprite;
		public img_index:Laya.Image;
		public img_null:Laya.Image;
		public img_head:Laya.Image;
		public img_award:Laya.Image;
		public img_no:Laya.Image;
		public img_get:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/InviteFriendsIndexView");
        }
    }
    REG("ui.game.uiView.InviteFriendsIndexViewUI",InviteFriendsIndexViewUI);
    export class InviteFriendsViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtInvite:Laya.Image;
		public panelInva:Laya.Panel;
		public boxInva:Laya.Box;
		public btn_close:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/InviteFriendsView");
        }
    }
    REG("ui.game.uiView.InviteFriendsViewUI",InviteFriendsViewUI);
    export class LevelIndexViewUI extends Laya.Scene {
		public spBg:Laya.Sprite;
		public levelNum:Laya.Sprite;
		public spG:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/LevelIndexView");
        }
    }
    REG("ui.game.uiView.LevelIndexViewUI",LevelIndexViewUI);
    export class LevelViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtHome:Laya.Image;
		public levelPanel:Laya.Panel;
		public levelBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/LevelView");
        }
    }
    REG("ui.game.uiView.LevelViewUI",LevelViewUI);
    export class MoreGameOperReqIndexUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
		public lableCount:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperReqIndex");
        }
    }
    REG("ui.game.uiView.MoreGameOperReqIndexUI",MoreGameOperReqIndexUI);
    export class MoreGameOperRequestUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public lableTitle:Laya.Label;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperRequest");
        }
    }
    REG("ui.game.uiView.MoreGameOperRequestUI",MoreGameOperRequestUI);
    export class ShareRecordVideoSkinViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public shareGlodCount:Laya.Image;
		public btn_shareVideo:Laya.Button;
		public btn_cancel:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/ShareRecordVideoSkinView");
        }
    }
    REG("ui.game.uiView.ShareRecordVideoSkinViewUI",ShareRecordVideoSkinViewUI);
    export class SignViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public boxItem:Laya.Box;
		public spWorldLeft:Laya.Sprite;
		public spWorldRight:Laya.Sprite;
		public imageBtSign:Laya.Image;
		public boxDouble:Laya.Box;
		public btDouble:Laya.Sprite;
		public spDouble:Laya.Sprite;
		public spTomorrow:Laya.Sprite;
		public spBtClose:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SignView");
        }
    }
    REG("ui.game.uiView.SignViewUI",SignViewUI);
    export class SkinItemViewUI extends Laya.Scene {
		public imageBg:Laya.Image;
		public imageSkinReal:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SkinItemView");
        }
    }
    REG("ui.game.uiView.SkinItemViewUI",SkinItemViewUI);
    export class SkinViewUI extends Laya.Scene {
		public imageBtToHome:Laya.Image;
		public panelSkin:Laya.Panel;
		public boxSkins:Laya.HBox;
		public imageBtWatchViceo:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareName:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SkinView");
        }
    }
    REG("ui.game.uiView.SkinViewUI",SkinViewUI);
    export class SuccessfulEntryOneViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public spTimeDown:Laya.Sprite;
		public imageParValue:Laya.Image;
		public imageBt:Laya.Image;
		public imageHand:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryOneView");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryOneViewUI",SuccessfulEntryOneViewUI);
    export class SuccessfulEntryThreeViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public boxGameData:Laya.Box;
		public box_award:Laya.Box;
		public spGlodAdd:Laya.Sprite;
		public imageGoodsTypeUp:Laya.Image;
		public btLable:Laya.Sprite;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spCountAddMore:Laya.Sprite;
		public spCost:Laya.Sprite;
		public imageBtShare:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareGameName:Laya.Image;
		public ttGoodsType:Laya.Image;
		public ttSpecial:Laya.Sprite;
		public shareGlodCount:Laya.Sprite;
		public imageBtRestart:Laya.Box;
		public spCostPs:Laya.Sprite;
		public box_double:Laya.Box;
		public btDouble:Laya.Sprite;
		public spDouble:Laya.Sprite;
		public lableDesc:Laya.Label;
		public imageWeCatMoreGame:Laya.Image;
		public panelWeCatMoreGame:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public box_content:Laya.Box;
		public box_wecat:Laya.Box;
		public imageBtToHome:Laya.Image;
		public btNextLevel:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryThreeView");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryThreeViewUI",SuccessfulEntryThreeViewUI);
    export class VentonesangerViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public image_change:Laya.Image;
		public imageValue:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/VentonesangerView");
        }
    }
    REG("ui.game.uiView.VentonesangerViewUI",VentonesangerViewUI);
    export class WeCatMoreGameItemOneUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameItemOne");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameItemOneUI",WeCatMoreGameItemOneUI);
    export class WeCatMoreGameItemTwoUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameItemTwo");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameItemTwoUI",WeCatMoreGameItemTwoUI);
    export class WeCatMoreGameViewUI extends Laya.Scene {
		public boxWeCatMoreGame:Laya.Box;
		public imageBg:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtWeCat:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameView");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameViewUI",WeCatMoreGameViewUI);
}
export module ui.game.uiView.lottery {
    export class LotterPopSceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public icon_title:Laya.Image;
		public box_count:Laya.Image;
		public btn_rfeceive:Laya.Image;
		public omg_r_video:Laya.Image;
		public btn_double:Laya.Image;
		public box_double:Laya.Box;
		public img_double:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotterPopScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterPopSceneUI",LotterPopSceneUI);
    export class LotterySceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public img_lottery:Laya.Image;
		public btn_lottery:Laya.Button;
		public img_video:Laya.Image;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotteryScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterySceneUI",LotterySceneUI);
    export class LotterySelSceneUI extends Laya.Scene {
		public img_lottery:Laya.Image;
		public btn_lottery:Laya.Button;
		public img_video:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotterySelScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterySelSceneUI",LotterySelSceneUI);
}
export module ui.game.uiView.wecat {
    export class MoreGameItemViewUI extends Laya.Scene {
		public goBtn:Laya.Button;
		public headiconImg:Laya.Image;
		public desLabel:Laya.Label;
		public titleLabel:Laya.Label;
		public baokuanImg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameItemView");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameItemViewUI",MoreGameItemViewUI);
    export class MoreGameOperRequestTwoUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameOperRequestTwo");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameOperRequestTwoUI",MoreGameOperRequestTwoUI);
    export class MoreGameRandomGameBox713UI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
		public imageRandom:Laya.Image;
		public lableTitle:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameRandomGameBox713");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameRandomGameBox713UI",MoreGameRandomGameBox713UI);
    export class MoreGameRandomGameBox713TempUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
		public imageRandom:Laya.Image;
		public lableTitle:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameRandomGameBox713Temp");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameRandomGameBox713TempUI",MoreGameRandomGameBox713TempUI);
    export class MoreGameRandomGameBoxItem713UI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameRandomGameBoxItem713");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameRandomGameBoxItem713UI",MoreGameRandomGameBoxItem713UI);
    export class MoreGameViewUI extends Laya.Scene {
		public tLabel:Laya.Label;
		public image_back:Laya.Image;
		public stPanel:Laya.Panel;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/MoreGameView");
        }
    }
    REG("ui.game.uiView.wecat.MoreGameViewUI",MoreGameViewUI);
    export class ShowMoreGameInfoInViewUI extends Laya.Scene {
		public box_wecat:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/ShowMoreGameInfoInView");
        }
    }
    REG("ui.game.uiView.wecat.ShowMoreGameInfoInViewUI",ShowMoreGameInfoInViewUI);
    export class ShowMoreGameInfoItemUI extends Laya.Scene {
		public image_icon:Laya.Image;
		public lable_name:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/ShowMoreGameInfoItem");
        }
    }
    REG("ui.game.uiView.wecat.ShowMoreGameInfoItemUI",ShowMoreGameInfoItemUI);
    export class WeCatMoreGameItemOne713BigUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/wecat/WeCatMoreGameItemOne713Big");
        }
    }
    REG("ui.game.uiView.wecat.WeCatMoreGameItemOne713BigUI",WeCatMoreGameItemOne713BigUI);
}